# Using spring-ai-starter-mcp-server-webmvc


spring:
  application:
    name: mcp-server
  ai:
    mcp:
      server:
        name: mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "提供城市名称，查询城市天气数据"
        annotation-scanner:
          enabled: true
        protocol: streamable


server:
  port: 8888